<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
    </ul>
</nav>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $('body').on('click', '#vertical-menu .navigation ul li .ui-menu-icon',function (e) {
            e.preventDefault();
            $(this).parent().next('.submenu').toggleClass('active');
            if($(this).hasClass('open')) {
                $(this).removeClass('open')
            }else {
                $(this).addClass('open');
            }
        });

        $(window).on('resize', function(){
            moveMainMenu();
        });

        function moveMainMenu() {
            if($(window).width() < 992) {
                $('#navigation-mobile').prepend($('.main-megamenu'));
            } else {
                $('.header-bottom > .container > .row').append($('.main-megamenu'))
            }
        }

        moveMainMenu();

        $('body').on('click', '#horizontal-menu .ui-icon',function (e) {
            if($(window).width() < 993) {
                e.preventDefault();
                $(this).parent().next('ul').toggleClass('active');
                if($(this).parent().parent('.ui-menu-icon').hasClass('open')) {
                    $(this).parent().parent('.ui-menu-icon').removeClass('open')
                }else {
                    $(this).parent().parent('.ui-menu-icon')    .addClass('open');
                }
            }
        });

    });
</script>